export const TELEMETRY_CONFIG = {
  endpoint: "/t/cli",
  sessionIdLength: 12,
  maxQueryLength: 200,
  maxMetadataSize: 2048,
  timeoutMs: 3000,
  envVars: {
    disableTelemetry: "DISABLE_TELEMETRY",
    doNotTrack: "DO_NOT_TRACK",
  },
} as const;

export const TELEMETRY_COMMANDS = {
  generate: "generate",
  auth: "auth",
  login: "login",
  credits: "credits",
  whoami: "whoami",
  doctor: "doctor",
  reset: "reset",
  update: "update",
  search: "search",
  resources: "resources",
  "config:get": "config:get",
  "config:set": "config:set",
  "config:unset": "config:unset",
  "skill:info": "skill:info",
  "skill:install": "skill:install",
  "skill:uninstall": "skill:uninstall",
  "skill:list": "skill:list",
  "skill:update": "skill:update",
  "skill:search": "skill:search",
  "outputs:list": "outputs:list",
  "outputs:get": "outputs:get",
} as const;

export const TELEMETRY_WHITELIST: Record<string, readonly string[]> = {
  [TELEMETRY_COMMANDS.generate]: [
    "skillSlug",
    "model",
    "success",
    "errorType",
    "errorData",
    "durationMs",
  ],
  [TELEMETRY_COMMANDS["skill:install"]]: [
    "skillSlug",
    "agents",
    "success",
    "errorType",
    "errorData",
    "durationMs",
  ],
  [TELEMETRY_COMMANDS["skill:uninstall"]]: [
    "skillSlug",
    "success",
    "errorType",
    "errorData",
    "durationMs",
  ],
  [TELEMETRY_COMMANDS["skill:search"]]: [
    "query",
    "resultCount",
    "success",
    "durationMs",
  ],
  [TELEMETRY_COMMANDS["skill:info"]]: [
    "skillSlug",
    "success",
    "errorType",
    "errorData",
    "durationMs",
  ],
  [TELEMETRY_COMMANDS["skill:list"]]: [
    "success",
    "resultCount",
    "errorType",
    "errorData",
    "durationMs",
  ],
  [TELEMETRY_COMMANDS["skill:update"]]: [
    "skillSlug",
    "success",
    "errorType",
    "errorData",
    "durationMs",
  ],
  [TELEMETRY_COMMANDS.search]: [
    "query",
    "resultCount",
    "success",
    "errorType",
    "errorData",
    "durationMs",
  ],
  [TELEMETRY_COMMANDS["config:get"]]: [
    "key",
    "success",
    "errorType",
    "errorData",
    "durationMs",
  ],
  [TELEMETRY_COMMANDS["config:set"]]: [
    "key",
    "success",
    "errorType",
    "errorData",
    "durationMs",
  ],
  [TELEMETRY_COMMANDS["config:unset"]]: [
    "key",
    "success",
    "errorType",
    "errorData",
    "durationMs",
  ],
  [TELEMETRY_COMMANDS.auth]: ["success", "errorType", "durationMs"],
  [TELEMETRY_COMMANDS.login]: ["success", "errorType", "durationMs"],
  [TELEMETRY_COMMANDS.credits]: [
    "success",
    "errorType",
    "errorData",
    "durationMs",
  ],
  [TELEMETRY_COMMANDS.whoami]: [
    "success",
    "errorType",
    "errorData",
    "durationMs",
  ],
  [TELEMETRY_COMMANDS.doctor]: [
    "success",
    "errorType",
    "errorData",
    "durationMs",
  ],
  [TELEMETRY_COMMANDS.reset]: [
    "success",
    "errorType",
    "errorData",
    "durationMs",
  ],
  [TELEMETRY_COMMANDS.update]: [
    "success",
    "errorType",
    "errorData",
    "durationMs",
  ],
  [TELEMETRY_COMMANDS.resources]: [
    "success",
    "resultCount",
    "errorType",
    "errorData",
    "durationMs",
  ],
  [TELEMETRY_COMMANDS["outputs:list"]]: [
    "success",
    "resultCount",
    "errorType",
    "errorData",
    "durationMs",
  ],
  [TELEMETRY_COMMANDS["outputs:get"]]: [
    "success",
    "errorType",
    "errorData",
    "durationMs",
  ],
} as const;
